---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-configmap
data:
  9999: "default/ops-lbs-py-office:9999"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-configmap
data:
  9998: "default/ops-lbs-py-office:9998"
---
   
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        imagePullPolicy: Always
        image: docker.idc.cedu.cn/ops-lbs-py
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: kube-system
  labels:
    k8s-app: default-http-backend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: tcp
    port: 9999
    targetPort: 9999
    protocol: TCP
  - name: udp
    port: 9998
    targetPort: 9998
    protocol: udp
  selector:
    k8s-app: default-http-backend
  type: ClusterIP
  clusterIP: None

  ####/usr/local/kubernetes/server/bin/nginx-ingress-controller --default-ssl-certificate=default/idc-ssl-cert --sync-period=10s --default-backend-service=kube-system/ops-lbs-py-office --tcp-services-configmap=default/tcp-configmap --udp-services-configmap=default/udp-configmap
